CREATE TABLE IF NOT EXISTS Waste_Categories(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    RECYCLABLE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS Disposal_Tips(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Recycle_Tips(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
);