package com.enviro.assessment.grad001.bennylebelo.models;

import jakarta.validation.constraints.NotEmpty;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;


/**
 * Represents a disposal tip, including a category and a description.
 * This class maps to the "DISPOSAL_TIPS" table in the database.
 */
@Table("DISPOSAL_TIPS")
public class DisposalTip {
    @Id
    private Integer id;

    @NotEmpty(message= "Field may not be empty")
    private String category;
    @NotEmpty(message= "Field may not be empty")
    private String description;

    public DisposalTip() {
    }

    /**
     * Constructor with category and description.
     * 
     * @param category The category of the disposal tip.
     * @param description The description of the disposal tip.
     */
    public DisposalTip(String category, String description) {
        //Id is auto generated by SQL schema setup, Not required in constructor
        this.category = category;
        this.description = description;
    }


    //Getters & Setters
    public Integer getId() {
        return id;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}